initial
GSA/notifications-api pull request #1272
Opened 2024-08-15 17:31 UTC by terrazoon

*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a detailed description here.

## TODO (optional)

* [ ] TODO item 1
* [ ] TODO item 2
* [ ] TODO item ...

## Security Considerations

* Consideration 1
* Consideration 2
* Consideration ...

2024-08-22 18:39 UTC, ccostino commented
Looks like this needs another merge from `main`, @terrazoon; could you also please update the PR description and details?  Thank you! 🙂

2024-08-28 21:13 UTC, ccostino commented
D'oh, style check fail; also PR still needs a proper description! 🙂

2024-09-04 20:24 UTC, ccostino approved these changes
Awesome @terrazoon, thank you for this cleanup!  This will help improve logging going forward, and nice catch with several of the older debug statements or other things that should not be logged as well!

2024-09-09 16:22 UTC, xlorepdarkhelm requested changes
See my notes.

2024-09-11 16:57 UTC, terrazoon commented on tests/app/test_cronitor.py
>      mock_logger.error.assert_called_with(
in this particular case, it is not because cronitor is explicitly doing an error message and not an exception.

2024-09-11 16:57 UTC, xlorepdarkhelm approved these changes
LGTM

2024-09-11 17:30 UTC, merged