fix inbound_number_dao
GSA/notifications-api pull request #1374
Opened 2024-10-17 17:02 UTC by terrazoon

*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a detailed description here.

## TODO (optional)

* [ ] TODO item 1
* [ ] TODO item 2
* [ ] TODO item ...

## Security Considerations

* Consideration 1
* Consideration 2
* Consideration ...

2024-10-22 19:26 UTC, xlorepdarkhelm requested changes
Looks good, but I saw a couple print statements, should they be removed?

2024-10-22 19:26 UTC, xlorepdarkhelm commented on app/inbound_sms/rest.py
> +    print(f"RESULTS HAS_NEXT {results.has_next}")
prints?

2024-10-22 20:36 UTC, terrazoon commented on app/inbound_sms/rest.py
> +    print(f"RESULTS HAS_NEXT {results.has_next}")
oops yes.  Thanks!

2024-10-29 21:13 UTC, ccostino reviewed
Thanks, @terrazoon!  One quick question on another `print` statement but otherwise all is good!

2024-10-29 21:13 UTC, ccostino commented on tests/app/dao/test_fact_notification_status_dao.py
> +    print(results)
Is this `print` still necessary?

2024-10-30 18:22 UTC, ccostino approved these changes
Thanks, @terrazoon! 🎉 

@xlorepdarkhelm, looks like you need to review again as well. 🙂

2024-10-30 19:42 UTC, A-Shumway42 approved these changes
I like the changes. Feels easier to read for me. No concerns here!

2024-10-30 20:51 UTC, merged