fix more sqlalchemy
GSA/notifications-api pull request #1417
Opened 2024-11-14 19:43 UTC by terrazoon

*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a detailed description here.

## TODO (optional)

* [ ] TODO item 1
* [ ] TODO item 2
* [ ] TODO item ...

## Security Considerations

* Consideration 1
* Consideration 2
* Consideration ...

2024-11-15 15:23 UTC, xlorepdarkhelm approved these changes

2024-11-20 13:37 UTC, xlorepdarkhelm approved these changes

2024-11-21 17:57 UTC, terrazoon commented on app/dao/fact_billing_dao.py
> +    allowance_left_at_start_date_querie = fetch_sms_free_allowance_remainder_until_date(
I've changed all the querie to stmt, with the side effect that you will now see sub stmt in places.

2024-12-12 16:28 UTC, xlorepdarkhelm commented on app/dao/api_key_dao.py
> +            .scalars()
See note above about `scalars()` and `filter_by()`

2024-12-19 15:15 UTC, terrazoon commented on app/dao/fact_billing_dao.py
> +            allowance_left_at_start_date_querie.c.sms_remainder,
fixed

2024-12-19 15:15 UTC, terrazoon commented on tests/app/dao/test_fact_processing_time_dao.py
> +    print(f"HERE ARE THE RESULTS {results}")
fixed

2024-12-19 15:53 UTC, terrazoon commented on app/dao/api_key_dao.py
> +        .scalars()
I fixed all the filter_bys but we need the scalars.  99.999% of the time we need scalars()

2024-12-19 16:29 UTC, xlorepdarkhelm requested changes
There are some cases of `.filter_by()` and `.filter()` which are in the statements. These should be `.where()` I believe, as the current standard looks more SQL-like rather than ORM-like.

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/celery/scheduled_tasks.py
> +    incomplete_in_progress_jobs = select(Job).filter(
Should this be a `.filter()` rather than a `.where()`?

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/service_callback_api_dao.py
> +            select(ServiceCallbackApi).filter_by(
`filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
> +        substmt = substmt.filter(Notification.key_type != KeyType.TEST)
`.filter()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
>          .filter(
`.filter()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/email_branding_dao.py
> +        db.session.execute(select(EmailBranding).filter_by(id=email_branding_id))
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/email_branding_dao.py
> +        db.session.execute(select(EmailBranding).filter_by(name=email_branding_name))
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/invited_org_user_dao.py
> +            select(InvitedOrganizationUser).filter_by(
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/invited_org_user_dao.py
> +            select(InvitedOrganizationUser).filter_by(id=invited_org_user_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/invited_org_user_dao.py
> +            select(InvitedOrganizationUser).filter_by(organization_id=organization_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/notifications_dao.py
> +    stmt = select(Notification).filter_by(service_id=service_id, job_id=job_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +            delete(self.Meta.model).filter_by(user=user, service=service)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +        db.session.execute(delete(self.Meta.model).filter_by(user=user))
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +                .filter_by(user_id=user_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +                .filter_by(active=True)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +                .filter_by(user_id=user_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/permissions_dao.py
> +                .filter_by(active=True, id=service_id)
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/service_callback_api_dao.py
> +            select(ServiceCallbackApi).filter_by(
`.filter_by()`

2024-12-19 16:29 UTC, xlorepdarkhelm commented on app/dao/service_callback_api_dao.py
> +            select(ServiceCallbackApi).filter_by(
`.filter_by()`

2024-12-20 15:38 UTC, xlorepdarkhelm requested changes
More filter() and filter_by() found. I actually went through and identified all the places I saw it in the code this time.

Might be good to search through the codebase for `.filter(` and `.filter_by(` to find the remaining ones.

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/fact_billing_dao.py
>          .filter(
Found another one.

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/fact_notification_status_dao.py
> +            substmt = substmt.filter(Notification.key_type != KeyType.TEST)
And another one

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/fact_notification_status_dao.py
> +        stmt = stmt.filter(
And another one.

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
>          stmt = stmt.filter(Service.active)
Here

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
>      stmt = delete(TemplateRedacted).filter(TemplateRedacted.template_id.in_(subq))
Here

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
>          select(VerifyCode).join(User).filter(User.id.in_([x.id for x in service.users]))
Here

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
> +        substmt = substmt.filter(Notification.key_type != KeyType.TEST)
Still here

2024-12-20 15:38 UTC, xlorepdarkhelm commented on app/dao/services_dao.py
>          .filter(
Still here

2025-01-13 21:28 UTC, ccostino commented
Looks like this PR needs another quick sync with `main` @terrazoon - thanks!

2025-01-21 16:55 UTC, ccostino reviewed
Thanks a ton for all of this, @terrazoon!

I only had two remaining questions to check on quick.  Thanks for calling out the pagination within the tests, too.  As long as those results are working as expected I think that's okay for now and we can clean that up more afterward.

2025-01-21 16:55 UTC, ccostino commented on app/config.py
> +                "schedule": crontab(minute="*/2"),
This was an adjustment we made recently, right?  Did it not stick, or was it just done in this PR?

2025-01-21 16:55 UTC, ccostino commented on app/dao/inbound_sms_dao.py
> +    pagination = Pagination(paginated_items, page, page_size, total_items)
Given that `page` is always set to `1`, this won't impact seeing the results we except, right?  Asked another way: this won't result us in always getting back just the first page of results, right?

2025-01-21 17:35 UTC, xlorepdarkhelm approved these changes

2025-01-21 17:41 UTC, terrazoon commented on app/dao/inbound_sms_dao.py
> +    pagination = Pagination(paginated_items, page, page_size, total_items)
It's sort of moot since this is for inbound sms, which we don't even support currently.

2025-01-21 17:42 UTC, terrazoon commented on app/config.py
> +                "schedule": crontab(minute="*/2"),
ha did I make this change?  I have no memory of it!

2025-01-21 17:43 UTC, ccostino commented on app/dao/inbound_sms_dao.py
> +    pagination = Pagination(paginated_items, page, page_size, total_items)
Thanks for clarifying!

2025-01-21 18:46 UTC, ccostino approved these changes
Thanks again, @terrazoon!

2025-01-21 18:51 UTC, merged