SMS provider cleanup
GSA/notifications-api pull request #157
Opened 2022-12-22 15:28 UTC by rahearn

Removes most references to MMG and all references to Firetext.

MMG examples are kept around in two situations where SNS implementation is not complete:

1. delivery receipts (work to be tracked/created under #152)
3. inbound SMS (work to be tracked under #156)

2022-12-23 20:16 UTC, stvnrlly requested changes
Thanks for tackling this, and it's nice to see how this sets up the next steps for delivery receipts and inbound messages.

Just a couple questions about small details.

2023-01-03 15:09 UTC, rahearn commented on app/notifications/receive_notifications.py
> +def strip_leading_plus_one(number):
I'm going to take a closer look at this method while working on #135

2023-01-03 15:13 UTC, rahearn commented on migrations/versions/0382_remove_old_sms_providers_.py
> +    raise Exception("Irreversible migration")
We could put entries back into `provider_details` but entires in `provider_details_history` will be lost, which is why I went with irreversible.

In my experience, rollbacks don't generally happen that often, and even less likely to be doing a multi-revision downgrade, at least as long as you're deploying code anywhere close to regularly.

2023-01-04 21:57 UTC, stvnrlly commented on app/notifications/receive_notifications.py
> +def strip_leading_plus_one(number):
It looks like my approach wouldn't work: those numbers are also 11 digits. I'll make a note over in that issue.

2023-01-04 22:03 UTC, stvnrlly commented on migrations/versions/0382_remove_old_sms_providers_.py
> +    raise Exception("Irreversible migration")
My initial thought was that `provider_details_history` would be ok to lose, but you're right that this should be considered irreversible in any production system.

2023-01-04 22:03 UTC, stvnrlly approved these changes

2023-01-05 12:52 UTC, merged