notify-136 change financial year starting in april to calendar year
GSA/notifications-api pull request #278
Opened 2023-05-16 19:30 UTC by terrazoon

2023-06-08 20:17 UTC, stvnrlly requested changes

2023-06-08 20:17 UTC, stvnrlly commented on app/dao/date_util.py
>  def get_financial_year(year):
Let's update this function name to some thing like `get_calendar_year()`

2023-06-08 20:17 UTC, stvnrlly commented on app/dao/date_util.py
>  def get_current_financial_year():
As above, let's update the function name.

2023-06-08 20:17 UTC, stvnrlly commented on app/dao/date_util.py
>       This function converts the start of the financial year April 1, 00:00 as BST (British Standard Time) to UTC,
This comment should be updated to reflect the change.

2023-06-14 15:31 UTC, ccostino reviewed
I took another look through this with the changes made from the previous suggestions and it looks good to go from my side!

@stvnrlly, was there anything else that had to happen with this before we approve?

2023-06-14 15:32 UTC, ccostino commented
Noting that given the age of the PR we may need to update with `main`, but it looks like this can still be merged without an issue according to GitHub.

2023-06-14 20:18 UTC, stvnrlly approved these changes

2023-06-14 20:19 UTC, merged