Package del/fai/pen counts
GSA/notifications-api pull request #780
Opened 2024-01-31 17:36 UTC by A-Shumway42

Added helper methods in `notifications_dao.py` to retrieve counts for `pending`, `failed`, and `delivered`.

Fixed tests with appropriate mocks in `test_get_service_by_id()`.

2024-02-05 21:54 UTC, ccostino commented
@A-Shumway42 is there an issue that this PR is associated with, or other work that is depending on it that we could reference here just for broader context?  Thanks!

2024-03-04 15:40 UTC, ccostino commented
@A-Shumway42 this will need to be updated with the recent changes merged into the API.

Once that's done, is this ready for full review?  If it is, let's get this ready for peer review. Thanks!

2024-03-14 19:13 UTC, xlorepdarkhelm requested changes
There are some changes to how the constants are used now with the enums in place. See comments below.

2024-03-14 19:13 UTC, xlorepdarkhelm commented on app/dao/notifications_dao.py
> +    NOTIFICATION_DELIVERED,
This will not work, as these strings simply do not exist any more. This needs to be adjusted to use app.enums and load/use the correct enums.

2024-03-14 19:13 UTC, xlorepdarkhelm commented on app/dao/notifications_dao.py
> +        status=NOTIFICATION_DELIVERED,
NOTIFICATION_DELIVERED has been changed to NotificationStatus.DELIVERED

2024-06-06 14:40 UTC, ccostino commented
Thanks again, @A-Shumway42!  At this point, we've been taking things in a different direction and don't need to continue with this path, so we're closing the PR.

2024-06-06 14:40 UTC, closed without merging