remove unused dependencies (notify-api-375)
GSA/notifications-api pull request #796
Opened 2024-02-08 19:46 UTC by terrazoon

2024-03-04 16:57 UTC, A-Shumway42 approved these changes
Looks good to me. deptry tool seems really neat!

2024-03-08 20:43 UTC, ccostino requested changes
Thanks, @terrazoon!

This is handy for sure; is there a high degree of confidence of what this is removing vs. changing?  Would it make more sense to tackle this after seeing what we can do about eliminating notification-utils completely by consolidating into the admin and/or API repos?

If we feel this is still safe to do now, I did note a couple of things that I think to be adjusted before we can merge it.  Thanks!

2024-03-08 20:43 UTC, ccostino commented on pyproject.toml
> +deptry = "==0.8.0"
`deptry` should be a development dependency, right?  It's only used by us locally with the `make` command?

2024-03-08 20:43 UTC, ccostino commented on pyproject.toml
> +eventlet = "==0.34.3"
This is downgrading `eventlet` for some reason - it's marked at `0.35.2` above, and I know we recently updated it from Dependabot.

2024-03-14 17:11 UTC, terrazoon commented
> Thanks, @terrazoon!
> 
> This is handy for sure; is there a high degree of confidence of what this is removing vs. changing? Would it make more sense to tackle this after seeing what we can do about eliminating notification-utils completely by consolidating into the admin and/or API repos?
> 
> If we feel this is still safe to do now, I did note a couple of things that I think to be adjusted before we can merge it. Thanks!

Well, if we don't trust the tool we have to do it by hand.  Would by hand be more reliable?  The ticket is to remove unused dependencies and from what I've seen this tool finds them.

2024-03-14 22:47 UTC, ccostino commented
We'll come back to this after the `ordered_set` and Python 3.12 update!

2024-03-22 18:25 UTC, closed without merging