python upgrade updates
GSA/notifications-api pull request #845
Opened 2024-03-12 00:46 UTC by samathad2023

## Description

This is Draft PR aims to upgrade project to python version 3.12.2.This PR encompasses changes in dependencies, configurations and code modifications to ensure compatibility with Python 3.12.2 .This commit is used to test the Admin and API.

This should include:

 install Python 3.12 via pyenv `pyenv install 3.12` 
 Create the new virtual environment against 3.12 
`cd notifications-api
pyenv virtualenv 3.12 notify-api-upgrade
pyenv local notify-utils-upgrade`
 Update the project to use the new virtual env that is 3.12-based (in the project root directory, `pyenv local notify-api-upgrade
`)
 Run `make bootstrap` to install the dependencies in the new virtual env

2024-03-13 16:40 UTC, xlorepdarkhelm approved these changes
LGTM

2024-03-13 16:47 UTC, xlorepdarkhelm requested changes
In app/enums.py, the import for `StrEnum` can be changed *and* the dependency on the `strenum` can be removed with the conversion to Python 3.12.

2024-03-13 21:24 UTC, xlorepdarkhelm reviewed
Made a note below. Nothing major, just cleanup work. I'll mark it as approved, just please remove those comments.

2024-03-13 21:24 UTC, xlorepdarkhelm commented on app/enums.py
> +from enum import StrEnum  # type: ignore [import-not-found]
you can remove the type: ignore comment.

Also, the comment below this can be removed, as it simply is describing what you did here.

2024-03-13 21:26 UTC, xlorepdarkhelm approved these changes
It was supposed to mark as approved, but decided to say there were changes requested.

2024-03-21 20:21 UTC, ccostino approved these changes
Thank you, @samathad2023! 🎉

2024-03-21 20:22 UTC, merged